# base docker image
FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04

RUN apt-get update
RUN apt-get install -y \
    git \
    software-properties-common \
    python3.11 \
    python3-pip 
    # add these packages for pdf exporting jupyter notebooks
    # texlive-xetex \
    # pandoc

# Install Jupyter and IPython kernel
RUN python3.11 -m pip install --upgrade pip \
    && python3.11 -m pip install \
    notebook ipykernel jupyterlab

# working directory
WORKDIR /app
COPY requirements.txt /app/

# installs
RUN pip install --upgrade pip && \
    pip install -r /app/requirements.txt